int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
int print_sign(int n);
int abs(int);
int _print_last_digit(int);
void jack_bauer(void);
void table_table(void);
int add(int, int);
void _print_to_98(int n);
void print_times_table(int n);
